import { League_Spartan, Montserrat } from 'next/font/google'
import './globals.css'

const leagueSpartan = League_Spartan({
  subsets: ['latin'],
  variable: '--font-league-spartan'
})
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat'
})

export const metadata = {
  title: 'Hiring Umar',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable} ${leagueSpartan.variable} scroll-smooth`}>
      <body>{children}</body>
    </html>
  )
}
